INTERACT_TIME = 0  # 交互时间
PROCESS_CUT_TIME = 4  # 切菜时间
PROCESS_POT_COOK_TIME = 16  # 煮时间
PROCESS_PAN_COOK_TIME = 24  # 煎时间
PROCESS_WASH_PLATE_TIME = 6  # 洗盘子时间
RETURN_DIRTY_PLATE_TIME = 10  # 上菜后脏盘子回收时间